<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405195605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_locked BOOLEAN NOT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, session_id INT NOT NULL, created_by_id INT NOT NULL, edited_by_id INT NOT NULL, locked_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_140AB620613FECDF ON page (session_id)');
        $this->addSql('CREATE INDEX IDX_140AB620B03A8386 ON page (created_by_id)');
        $this->addSql('CREATE INDEX IDX_140AB620DD7B2EBC ON page (edited_by_id)');
        $this->addSql('CREATE INDEX IDX_140AB6207A88E00 ON page (locked_by_id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620DD7B2EBC FOREIGN KEY (edited_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB6207A88E00 FOREIGN KEY (locked_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620613FECDF');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620B03A8386');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620DD7B2EBC');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB6207A88E00');
        $this->addSql('DROP TABLE page');
    }
}
