<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405194053 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pictures (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, size BIGINT NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id INT NOT NULL, add_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F7C2FC0613FECDF ON pictures (session_id)');
        $this->addSql('CREATE INDEX IDX_8F7C2FC017542AC5 ON pictures (add_by_id)');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC0613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC017542AC5 FOREIGN KEY (add_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC0613FECDF');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC017542AC5');
        $this->addSql('DROP TABLE pictures');
    }
}
