<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405190028 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE storage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE invitation ADD session_id INT NOT NULL');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F11D61A2613FECDF ON invitation (session_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE storage');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2613FECDF');
        $this->addSql('DROP INDEX IDX_F11D61A2613FECDF');
        $this->addSql('ALTER TABLE invitation DROP session_id');
    }
}
