<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405184323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, responce BOOLEAN NOT NULL, send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_id_id INT NOT NULL, receiver_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11D61A26061F7CF ON invitation (sender_id_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A2BE20CAB0 ON invitation (receiver_id_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(60) NOT NULL, is_blocked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A26061F7CF FOREIGN KEY (sender_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2BE20CAB0 FOREIGN KEY (receiver_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A26061F7CF');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2BE20CAB0');
        $this->addSql('DROP TABLE invitation');
        $this->addSql('DROP TABLE session');
    }
}
