<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405191926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6692B547597D3FE ON access (member_id)');
        $this->addSql('CREATE INDEX IDX_6692B54613FECDF ON access (session_id)');
        $this->addSql('ALTER TABLE access ADD CONSTRAINT FK_6692B547597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access ADD CONSTRAINT FK_6692B54613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access DROP CONSTRAINT FK_6692B547597D3FE');
        $this->addSql('ALTER TABLE access DROP CONSTRAINT FK_6692B54613FECDF');
        $this->addSql('DROP TABLE access');
    }
}
