<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405203952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE Accesses (acc_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acc_role VARCHAR(20) NOT NULL, acc_joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, acc_member_id INT NOT NULL, acc_session_id INT NOT NULL, PRIMARY KEY (acc_id))');
        $this->addSql('CREATE INDEX IDX_1B42A8B4916A110D ON Accesses (acc_member_id)');
        $this->addSql('CREATE INDEX IDX_1B42A8B4456FB2BB ON Accesses (acc_session_id)');
        $this->addSql('CREATE TABLE Invitations (inv_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inv_responce BOOLEAN NOT NULL, inv_send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inv_sender_id INT NOT NULL, inv_receiver_id INT NOT NULL, inv_session_id INT NOT NULL, PRIMARY KEY (inv_id))');
        $this->addSql('CREATE INDEX IDX_A5BB9F799D4CB64 ON Invitations (inv_sender_id)');
        $this->addSql('CREATE INDEX IDX_A5BB9F7956F3B1BC ON Invitations (inv_receiver_id)');
        $this->addSql('CREATE INDEX IDX_A5BB9F79A5A1561F ON Invitations (inv_session_id)');
        $this->addSql('CREATE TABLE Nodes (nod_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nod_path VARCHAR(255) NOT NULL, nod_size BIGINT NOT NULL, nod_name VARCHAR(80) NOT NULL, nod_type VARCHAR(10) NOT NULL, nod_session_id INT NOT NULL, nod_add_by INT NOT NULL, PRIMARY KEY (nod_id))');
        $this->addSql('CREATE INDEX IDX_DCFC2AF8FDD95639 ON Nodes (nod_session_id)');
        $this->addSql('CREATE INDEX IDX_DCFC2AF82CEEE1C9 ON Nodes (nod_add_by)');
        $this->addSql('CREATE TABLE Pages (pag_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pag_name VARCHAR(50) NOT NULL, pag_content TEXT DEFAULT NULL, pag_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pag_edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pag_is_locked BOOLEAN NOT NULL, pag_locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pag_session_id INT NOT NULL, pag_created_by INT NOT NULL, pag_edited_by INT NOT NULL, pag_locked_by INT DEFAULT NULL, PRIMARY KEY (pag_id))');
        $this->addSql('CREATE INDEX IDX_E1B5CA71DD88E195 ON Pages (pag_session_id)');
        $this->addSql('CREATE INDEX IDX_E1B5CA7162A5A61C ON Pages (pag_created_by)');
        $this->addSql('CREATE INDEX IDX_E1B5CA7172B590D ON Pages (pag_edited_by)');
        $this->addSql('CREATE INDEX IDX_E1B5CA71A0121C00 ON Pages (pag_locked_by)');
        $this->addSql('CREATE TABLE Reports (rep_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rep_subject VARCHAR(255) NOT NULL, rep_content TEXT NOT NULL, rep_send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rep_author_id INT NOT NULL, PRIMARY KEY (rep_id))');
        $this->addSql('CREATE INDEX IDX_3EA29ED9C36CFCD6 ON Reports (rep_author_id)');
        $this->addSql('CREATE TABLE Sessions (ses_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ses_name VARCHAR(60) NOT NULL, ses_is_blocked BOOLEAN NOT NULL, ses_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ses_last_activity TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ses_storage_id INT NOT NULL, PRIMARY KEY (ses_id))');
        $this->addSql('CREATE INDEX IDX_6316FF4553B44F14 ON Sessions (ses_storage_id)');
        $this->addSql('CREATE TABLE Storages (sto_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sto_name BIGINT NOT NULL, PRIMARY KEY (sto_id))');
        $this->addSql('ALTER TABLE Accesses ADD CONSTRAINT FK_1B42A8B4916A110D FOREIGN KEY (acc_member_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Accesses ADD CONSTRAINT FK_1B42A8B4456FB2BB FOREIGN KEY (acc_session_id) REFERENCES Sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F799D4CB64 FOREIGN KEY (inv_sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F7956F3B1BC FOREIGN KEY (inv_receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F79A5A1561F FOREIGN KEY (inv_session_id) REFERENCES Sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Nodes ADD CONSTRAINT FK_DCFC2AF8FDD95639 FOREIGN KEY (nod_session_id) REFERENCES Sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Nodes ADD CONSTRAINT FK_DCFC2AF82CEEE1C9 FOREIGN KEY (nod_add_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA71DD88E195 FOREIGN KEY (pag_session_id) REFERENCES Sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA7162A5A61C FOREIGN KEY (pag_created_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA7172B590D FOREIGN KEY (pag_edited_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA71A0121C00 FOREIGN KEY (pag_locked_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Reports ADD CONSTRAINT FK_3EA29ED9C36CFCD6 FOREIGN KEY (rep_author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Sessions ADD CONSTRAINT FK_6316FF4553B44F14 FOREIGN KEY (ses_storage_id) REFERENCES Storages (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access DROP CONSTRAINT fk_6692b54613fecdf');
        $this->addSql('ALTER TABLE access DROP CONSTRAINT fk_6692b547597d3fe');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT fk_f11d61a2cd53edb6');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT fk_f11d61a2613fecdf');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT fk_f11d61a2f624b39d');
        $this->addSql('ALTER TABLE node DROP CONSTRAINT fk_857fe84517542ac5');
        $this->addSql('ALTER TABLE node DROP CONSTRAINT fk_857fe845613fecdf');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT fk_140ab620dd7b2ebc');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT fk_140ab620613fecdf');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT fk_140ab620b03a8386');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT fk_140ab6207a88e00');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT fk_c42f7784f675f31b');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT fk_d044d5d45cc5db90');
        $this->addSql('DROP TABLE access');
        $this->addSql('DROP TABLE invitation');
        $this->addSql('DROP TABLE node');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE storage');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT fk_8f7c2fc017542ac5');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT fk_8f7c2fc0613fecdf');
        $this->addSql('DROP INDEX idx_8f7c2fc017542ac5');
        $this->addSql('DROP INDEX idx_8f7c2fc0613fecdf');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT pictures_pkey');
        $this->addSql('ALTER TABLE pictures ADD pic_session_id INT NOT NULL');
        $this->addSql('ALTER TABLE pictures ADD pic_add_by INT NOT NULL');
        $this->addSql('ALTER TABLE pictures DROP session_id');
        $this->addSql('ALTER TABLE pictures DROP add_by_id');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN id TO pic_id');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN path TO pic_path');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN size TO pic_size');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN name TO pic_name');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN created_at TO pic_created_at');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC0848D0987 FOREIGN KEY (pic_session_id) REFERENCES Sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC06C562001 FOREIGN KEY (pic_add_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8F7C2FC0848D0987 ON pictures (pic_session_id)');
        $this->addSql('CREATE INDEX IDX_8F7C2FC06C562001 ON pictures (pic_add_by)');
        $this->addSql('ALTER TABLE pictures ADD PRIMARY KEY (pic_id)');
        $this->addSql('DROP INDEX user_pkey');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('ALTER TABLE "user" ADD usr_name VARCHAR(60) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD usr_firstname VARCHAR(60) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD usr_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD usr_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD usr_ban_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP name');
        $this->addSql('ALTER TABLE "user" DROP firstname');
        $this->addSql('ALTER TABLE "user" DROP updated_at');
        $this->addSql('ALTER TABLE "user" DROP deleted_at');
        $this->addSql('ALTER TABLE "user" DROP ban_at');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN id TO usr_id');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN email TO usr_email');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN roles TO usr_roles');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN password TO usr_password');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN pseudo TO usr_pseudo');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN photo TO usr_photo');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN created_at TO usr_created_at');
        $this->addSql('ALTER TABLE "user" ADD PRIMARY KEY (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (usr_email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6692b54613fecdf ON access (session_id)');
        $this->addSql('CREATE INDEX idx_6692b547597d3fe ON access (member_id)');
        $this->addSql('CREATE TABLE invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, responce BOOLEAN NOT NULL, send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f11d61a2613fecdf ON invitation (session_id)');
        $this->addSql('CREATE INDEX idx_f11d61a2cd53edb6 ON invitation (receiver_id)');
        $this->addSql('CREATE INDEX idx_f11d61a2f624b39d ON invitation (sender_id)');
        $this->addSql('CREATE TABLE node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, size BIGINT NOT NULL, name VARCHAR(80) NOT NULL, type VARCHAR(10) NOT NULL, session_id INT NOT NULL, add_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_857fe845613fecdf ON node (session_id)');
        $this->addSql('CREATE INDEX idx_857fe84517542ac5 ON node (add_by_id)');
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_locked BOOLEAN NOT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, session_id INT NOT NULL, created_by_id INT NOT NULL, edited_by_id INT NOT NULL, locked_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_140ab620b03a8386 ON page (created_by_id)');
        $this->addSql('CREATE INDEX idx_140ab620613fecdf ON page (session_id)');
        $this->addSql('CREATE INDEX idx_140ab620dd7b2ebc ON page (edited_by_id)');
        $this->addSql('CREATE INDEX idx_140ab6207a88e00 ON page (locked_by_id)');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) NOT NULL, content TEXT NOT NULL, send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c42f7784f675f31b ON report (author_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(60) NOT NULL, is_blocked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, storage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d044d5d45cc5db90 ON session (storage_id)');
        $this->addSql('CREATE TABLE storage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE access ADD CONSTRAINT fk_6692b54613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE access ADD CONSTRAINT fk_6692b547597d3fe FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT fk_f11d61a2cd53edb6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT fk_f11d61a2613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT fk_f11d61a2f624b39d FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE node ADD CONSTRAINT fk_857fe84517542ac5 FOREIGN KEY (add_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE node ADD CONSTRAINT fk_857fe845613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_140ab620dd7b2ebc FOREIGN KEY (edited_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_140ab620613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_140ab620b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_140ab6207a88e00 FOREIGN KEY (locked_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT fk_c42f7784f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT fk_d044d5d45cc5db90 FOREIGN KEY (storage_id) REFERENCES storage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Accesses DROP CONSTRAINT FK_1B42A8B4916A110D');
        $this->addSql('ALTER TABLE Accesses DROP CONSTRAINT FK_1B42A8B4456FB2BB');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F799D4CB64');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F7956F3B1BC');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F79A5A1561F');
        $this->addSql('ALTER TABLE Nodes DROP CONSTRAINT FK_DCFC2AF8FDD95639');
        $this->addSql('ALTER TABLE Nodes DROP CONSTRAINT FK_DCFC2AF82CEEE1C9');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA71DD88E195');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA7162A5A61C');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA7172B590D');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA71A0121C00');
        $this->addSql('ALTER TABLE Reports DROP CONSTRAINT FK_3EA29ED9C36CFCD6');
        $this->addSql('ALTER TABLE Sessions DROP CONSTRAINT FK_6316FF4553B44F14');
        $this->addSql('DROP TABLE Accesses');
        $this->addSql('DROP TABLE Invitations');
        $this->addSql('DROP TABLE Nodes');
        $this->addSql('DROP TABLE Pages');
        $this->addSql('DROP TABLE Reports');
        $this->addSql('DROP TABLE Sessions');
        $this->addSql('DROP TABLE Storages');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC0848D0987');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC06C562001');
        $this->addSql('DROP INDEX IDX_8F7C2FC0848D0987');
        $this->addSql('DROP INDEX IDX_8F7C2FC06C562001');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT pictures_pkey');
        $this->addSql('ALTER TABLE pictures ADD session_id INT NOT NULL');
        $this->addSql('ALTER TABLE pictures ADD add_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE pictures DROP pic_session_id');
        $this->addSql('ALTER TABLE pictures DROP pic_add_by');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN pic_id TO id');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN pic_path TO path');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN pic_size TO size');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN pic_name TO name');
        $this->addSql('ALTER TABLE pictures RENAME COLUMN pic_created_at TO created_at');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT fk_8f7c2fc017542ac5 FOREIGN KEY (add_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT fk_8f7c2fc0613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_8f7c2fc017542ac5 ON pictures (add_by_id)');
        $this->addSql('CREATE INDEX idx_8f7c2fc0613fecdf ON pictures (session_id)');
        $this->addSql('ALTER TABLE pictures ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT "user_pkey"');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
        $this->addSql('ALTER TABLE "user" ADD name VARCHAR(60) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD firstname VARCHAR(60) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD ban_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP usr_name');
        $this->addSql('ALTER TABLE "user" DROP usr_firstname');
        $this->addSql('ALTER TABLE "user" DROP usr_updated_at');
        $this->addSql('ALTER TABLE "user" DROP usr_deleted_at');
        $this->addSql('ALTER TABLE "user" DROP usr_ban_at');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_id TO id');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_email TO email');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_roles TO roles');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_password TO password');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_pseudo TO pseudo');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_photo TO photo');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN usr_created_at TO created_at');
        $this->addSql('ALTER TABLE "user" ADD PRIMARY KEY (id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
    }
}
