<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407134726 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE Accesses (acc_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acc_role VARCHAR(20) NOT NULL, acc_joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, acc_member_id INT NOT NULL, acc_session_id INT NOT NULL, PRIMARY KEY (acc_id))');
        $this->addSql('CREATE INDEX IDX_1B42A8B4916A110D ON Accesses (acc_member_id)');
        $this->addSql('CREATE INDEX IDX_1B42A8B4456FB2BB ON Accesses (acc_session_id)');
        $this->addSql('CREATE TABLE Invitations (inv_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inv_responce BOOLEAN NOT NULL, inv_send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inv_sender_id INT NOT NULL, inv_receiver_id INT NOT NULL, inv_session_id INT NOT NULL, PRIMARY KEY (inv_id))');
        $this->addSql('CREATE INDEX IDX_A5BB9F799D4CB64 ON Invitations (inv_sender_id)');
        $this->addSql('CREATE INDEX IDX_A5BB9F7956F3B1BC ON Invitations (inv_receiver_id)');
        $this->addSql('CREATE INDEX IDX_A5BB9F79A5A1561F ON Invitations (inv_session_id)');
        $this->addSql('CREATE TABLE Nodes (nod_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nod_path VARCHAR(255) NOT NULL, nod_size BIGINT NOT NULL, nod_name VARCHAR(80) NOT NULL, nod_type VARCHAR(10) NOT NULL, nod_session_id INT NOT NULL, nod_add_by INT NOT NULL, nod_parent_id INT DEFAULT NULL, PRIMARY KEY (nod_id))');
        $this->addSql('CREATE INDEX IDX_DCFC2AF8FDD95639 ON Nodes (nod_session_id)');
        $this->addSql('CREATE INDEX IDX_DCFC2AF82CEEE1C9 ON Nodes (nod_add_by)');
        $this->addSql('CREATE INDEX IDX_DCFC2AF89DC685B4 ON Nodes (nod_parent_id)');
        $this->addSql('CREATE TABLE Pages (pag_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pag_name VARCHAR(50) NOT NULL, pag_content TEXT DEFAULT NULL, pag_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pag_edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pag_is_locked BOOLEAN NOT NULL, pag_locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pag_session_id INT NOT NULL, pag_created_by INT NOT NULL, pag_edited_by INT NOT NULL, pag_locked_by INT DEFAULT NULL, PRIMARY KEY (pag_id))');
        $this->addSql('CREATE INDEX IDX_E1B5CA71DD88E195 ON Pages (pag_session_id)');
        $this->addSql('CREATE INDEX IDX_E1B5CA7162A5A61C ON Pages (pag_created_by)');
        $this->addSql('CREATE INDEX IDX_E1B5CA7172B590D ON Pages (pag_edited_by)');
        $this->addSql('CREATE INDEX IDX_E1B5CA71A0121C00 ON Pages (pag_locked_by)');
        $this->addSql('CREATE TABLE Reports (rep_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rep_subject VARCHAR(255) NOT NULL, rep_content TEXT NOT NULL, rep_send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rep_author_id INT NOT NULL, PRIMARY KEY (rep_id))');
        $this->addSql('CREATE INDEX IDX_3EA29ED9C36CFCD6 ON Reports (rep_author_id)');
        $this->addSql('CREATE TABLE Sessions (ses_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ses_name VARCHAR(60) NOT NULL, ses_is_blocked BOOLEAN NOT NULL, ses_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ses_last_activity TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ses_storage_id INT NOT NULL, PRIMARY KEY (ses_id))');
        $this->addSql('CREATE INDEX IDX_6316FF4553B44F14 ON Sessions (ses_storage_id)');
        $this->addSql('CREATE TABLE Storages (sto_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sto_name BIGINT NOT NULL, PRIMARY KEY (sto_id))');
        $this->addSql('CREATE TABLE Users (usr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_email VARCHAR(180) NOT NULL, usr_roles JSON NOT NULL, usr_password VARCHAR(255) NOT NULL, usr_name VARCHAR(60) NOT NULL, usr_firstname VARCHAR(60) NOT NULL, usr_pseudo VARCHAR(60) DEFAULT NULL, usr_photo VARCHAR(100) DEFAULT NULL, usr_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usr_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usr_ban_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, usr_birthdate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (usr_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON Users (usr_email)');
        $this->addSql('CREATE TABLE pictures (pic_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pic_path VARCHAR(255) NOT NULL, pic_size BIGINT NOT NULL, pic_name VARCHAR(100) NOT NULL, pic_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pic_session_id INT NOT NULL, pic_add_by INT NOT NULL, PRIMARY KEY (pic_id))');
        $this->addSql('CREATE INDEX IDX_8F7C2FC0848D0987 ON pictures (pic_session_id)');
        $this->addSql('CREATE INDEX IDX_8F7C2FC06C562001 ON pictures (pic_add_by)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE Accesses ADD CONSTRAINT FK_1B42A8B4916A110D FOREIGN KEY (acc_member_id) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Accesses ADD CONSTRAINT FK_1B42A8B4456FB2BB FOREIGN KEY (acc_session_id) REFERENCES Sessions (ses_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F799D4CB64 FOREIGN KEY (inv_sender_id) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F7956F3B1BC FOREIGN KEY (inv_receiver_id) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Invitations ADD CONSTRAINT FK_A5BB9F79A5A1561F FOREIGN KEY (inv_session_id) REFERENCES Sessions (ses_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Nodes ADD CONSTRAINT FK_DCFC2AF8FDD95639 FOREIGN KEY (nod_session_id) REFERENCES Sessions (ses_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Nodes ADD CONSTRAINT FK_DCFC2AF82CEEE1C9 FOREIGN KEY (nod_add_by) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Nodes ADD CONSTRAINT FK_DCFC2AF89DC685B4 FOREIGN KEY (nod_parent_id) REFERENCES Nodes (nod_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA71DD88E195 FOREIGN KEY (pag_session_id) REFERENCES Sessions (ses_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA7162A5A61C FOREIGN KEY (pag_created_by) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA7172B590D FOREIGN KEY (pag_edited_by) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Pages ADD CONSTRAINT FK_E1B5CA71A0121C00 FOREIGN KEY (pag_locked_by) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Reports ADD CONSTRAINT FK_3EA29ED9C36CFCD6 FOREIGN KEY (rep_author_id) REFERENCES Users (usr_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Sessions ADD CONSTRAINT FK_6316FF4553B44F14 FOREIGN KEY (ses_storage_id) REFERENCES Storages (sto_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC0848D0987 FOREIGN KEY (pic_session_id) REFERENCES Sessions (ses_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pictures ADD CONSTRAINT FK_8F7C2FC06C562001 FOREIGN KEY (pic_add_by) REFERENCES Users (usr_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Accesses DROP CONSTRAINT FK_1B42A8B4916A110D');
        $this->addSql('ALTER TABLE Accesses DROP CONSTRAINT FK_1B42A8B4456FB2BB');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F799D4CB64');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F7956F3B1BC');
        $this->addSql('ALTER TABLE Invitations DROP CONSTRAINT FK_A5BB9F79A5A1561F');
        $this->addSql('ALTER TABLE Nodes DROP CONSTRAINT FK_DCFC2AF8FDD95639');
        $this->addSql('ALTER TABLE Nodes DROP CONSTRAINT FK_DCFC2AF82CEEE1C9');
        $this->addSql('ALTER TABLE Nodes DROP CONSTRAINT FK_DCFC2AF89DC685B4');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA71DD88E195');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA7162A5A61C');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA7172B590D');
        $this->addSql('ALTER TABLE Pages DROP CONSTRAINT FK_E1B5CA71A0121C00');
        $this->addSql('ALTER TABLE Reports DROP CONSTRAINT FK_3EA29ED9C36CFCD6');
        $this->addSql('ALTER TABLE Sessions DROP CONSTRAINT FK_6316FF4553B44F14');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC0848D0987');
        $this->addSql('ALTER TABLE pictures DROP CONSTRAINT FK_8F7C2FC06C562001');
        $this->addSql('DROP TABLE Accesses');
        $this->addSql('DROP TABLE Invitations');
        $this->addSql('DROP TABLE Nodes');
        $this->addSql('DROP TABLE Pages');
        $this->addSql('DROP TABLE Reports');
        $this->addSql('DROP TABLE Sessions');
        $this->addSql('DROP TABLE Storages');
        $this->addSql('DROP TABLE Users');
        $this->addSql('DROP TABLE pictures');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
